/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/angel_old_marble_version.glb 
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/angel-old-marble-version-2c879fc654b44f5e8d12527948535b51
Title: Angel (old marble version)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/angel_old_marble_version.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['SilverAngel_LP_Unwrap#1_0'].geometry} material={materials.Unwrap1} position={[-0.341, 1.342, -7.51]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/angel_old_marble_version.glb')
