/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/death_crowning_innocence_1896_Painting.glb 
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/death-crowning-innocence-1896-ebcbbe30d65a43fa96187ade879d43cd
Title: Death Crowning Innocence (1896)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/death_crowning_innocence_1896_Painting.glb')
  return (
    <group {...props} dispose={null}>
      {/* Removed the hardcoded rotation and scale to let App.jsx handle it via <Center> and modelData.scale */}
      <group scale={0.8}>
        <group position={[0, -2.722, -0.008]}>
          <mesh geometry={nodes['Obraz02_ready_Material_#37_0'].geometry} material={materials.Material_37} />
          <mesh geometry={nodes.Obraz02_ready_RamyLP_0.geometry} material={materials.RamyLP} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/death_crowning_innocence_1896_Painting.glb')
