/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/frank.glb 
Author: misterdevious (https://sketchfab.com/misterdevious)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/frank-0eb1f1757349489eab05a0f03cff5b46
Title: Frank
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/frank.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.336}>
        <mesh geometry={nodes.FranksC352SC130kDC32270kM2064k_0.geometry} material={materials['Franks.C352.SC130k.DC32270k.M2064k']} rotation={[-2.696, -0.624, -0.704]} scale={0.188} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/frank.glb')
