/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/louis_xiv_de_france_louvre_paris.glb 
Author: HoangHiepVu (https://sketchfab.com/HoangHiepVu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/louis-xiv-de-france-louvre-paris-a0cc0e7eee384c99838dff2857b8158c
Title: Louis XIV de France, Louvre, Paris
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/louis_xiv_de_france_louvre_paris.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 8.997, -2.251]} rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Model_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Model_0} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Model_0} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Model_1} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Model_1} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/louis_xiv_de_france_louvre_paris.glb')
