/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/painting_by_zdzislaw_beksinski_2.glb 
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/painting-by-zdzislaw-beksinski-2-da5bab909570476b951be08d6a9eecdc
Title: Painting by Zdzislaw Beksinski (2)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/painting_by_zdzislaw_beksinski_2.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.382}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.028, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Object004_Material_#89_0'].geometry} material={materials.Material_89} position={[0.04, -0.765, -2.904]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <mesh geometry={nodes.TylObrazu_RAMY_0.geometry} material={materials.RAMY} position={[0, 0.004, -0.129]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <group position={[0.04, -0.765, -2.904]}>
            <mesh geometry={nodes.Object003_RAMY_0.geometry} material={materials.RAMY} />
            <mesh geometry={nodes.Object003_OBRAZ_0.geometry} material={materials.OBRAZ} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/painting_by_zdzislaw_beksinski_2.glb')
