/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/the_thinker_by_auguste_rodin.glb 
Author: Rigsters (https://sketchfab.com/rigsters)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-thinker-by-auguste-rodin-08a1e693c9674a3292dec2298b09e0ae
Title: The Thinker by Auguste Rodin
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/the_thinker_by_auguste_rodin.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} position={[0.007, 0.001, 0.005]} rotation={[-1.576, -0.008, 0]} />
    </group>
  )
}

useGLTF.preload('/models/the_thinker_by_auguste_rodin.glb')
